package db

const (
	SelectResouceTotalCost = `
		SELECT "COST", COUNT(*) AS occurrences
		FROM "COST"
	    JOIN "RESOURCE" ON "COST"."RESOURCE_ID" = "RESOURCE"."RESOURCE_ID"
		WHERE "COST"."RESOURCE_ID" = $1
	    AND "RESOURCE"."COMPANY_ID" = $2
		AND "START_TIMESTAMP" > $3
		AND "END_TIMESTAMP" < $4
		GROUP BY "COST";
	`

	SelectResouceCost = `
		SELECT
	      "COST"."RESOURCE_ID",
	      "COST"."COST",
	      "COST"."AGGREGATE",
	      "COST"."START_TIMESTAMP",
	      "COST"."END_TIMESTAMP",
	      "COST"."CREATED_AT"
		FROM "COST"
	    JOIN "RESOURCE" ON "COST"."RESOURCE_ID" = "RESOURCE"."RESOURCE_ID"
		WHERE "COST"."RESOURCE_ID" = $1
		AND "RESOURCE"."COMPANY_ID" = $2
		AND "START_TIMESTAMP" > $3
		AND "END_TIMESTAMP" < $4
	`

	SelectResouceData = `
		SELECT
		  "METRIC_NAME",
		  "METRIC_VALUE",
		  "METRIC_UNIT",
		  "AGGREGATE",
		  "TIMESTAMP"
		FROM
		  "RESOURCE_DATA"
		JOIN
		  "RESOURCE" ON "RESOURCE_DATA"."RESOURCE_ID" = "RESOURCE"."RESOURCE_ID"
		WHERE
		  "RESOURCE_DATA"."RESOURCE_ID" = $1
		AND
		  "RESOURCE"."COMPANY_ID" = $2
		ORDER BY "TIMESTAMP" ASC;
	`

	SelectAllCompanyResources = `
		SELECT
			"RESOURCE_ID",
			"RESOURCE_NAME",
			"NAME" AS "RESOURCE_TYPE",
			"CREATED_AT"
		FROM
			"RESOURCE"
		JOIN
			"RESOURCE_TYPES" ON "RESOURCE"."TYPE_ID" = "RESOURCE_TYPES"."ID"
		WHERE
			"COMPANY_ID" = $1
	`

	SelectCompanyResource = `
		SELECT
			"RESOURCE_ID",
			"RESOURCE_NAME",
			"ACCOUNT_ROLE_ARN"
		FROM
			"RESOURCE"
		JOIN
			"ACCOUNT_ROLE" ON "RESOURCE"."COMPANY_ID" = "ACCOUNT_ROLE"."COMPANY_ID"
		WHERE
			"RESOURCE"."COMPANY_ID" = $1
		AND
			"RESOURCE_ID" = $2
	`
)
