name: Update Lambda

on:
  push:
    branches:
      - main # Trigger on push to the main branch

permissions:
  id-token: write # Enable OIDC token generation
  contents: read # Default read permission for repository content

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        lambda:
          - companies
          - users
          - resources

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Go
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.23" # Replace with your Go version

      # Build the Go binary for the current Lambda
      - name: Build Go binary
        working-directory: lambdas/${{ matrix.lambda }}
        run: |
          GOOS=linux GOARCH=arm64 go build -tags lambda.norpc -o bootstrap main.go router.go

      # Package the binary into a ZIP file
      - name: Package binary
        working-directory: lambdas/${{ matrix.lambda }}
        run: |
          zip function.zip bootstrap

      # Configure AWS credentials using OIDC
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::128114088254:role/valtro-core-github
          aws-region: us-east-1
        env:
          ACTIONS_STEP_DEBUG: true

      # Deploy the Lambda or perform other AWS actions
      - name: Deploy Lambda
        working-directory: lambdas/${{ matrix.lambda }}
        run: |
          aws lambda update-function-code \
            --function-name alpha-${{ matrix.lambda }} \
            --zip-file fileb://function.zip
